REM THIS FILE IS TO RUN BACK-END PART FOR LYCEENA

SET DATASOURCE_URL=jdbc:h2:tcp://localhost/~/LYCEENA_H2_PROD
SET SERVER_PORT=7707
SET CORS_ALLOWED_ORIGINS=http://192.168.0.14:8080
SET DDL_AUTO=update

java -jar lyceena-1.0-SNAPSHOT.jar
