server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/LYCEENA_AUTH_H2

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: bael-admin
      password: admin
    realmImportFile: lyceena-realm.json
  connectionsJpa:
    url: jdbc:h2:tcp://localhost:9092/~/LYCEENA_AUTH_H2
