package com.zka.lyceena.constants;

public class StaticData {
    public static final String[][] STUDENTS = {
            {"Werner", "Jenkins"},
            {"Glenn", "Gramlich"},
            {"Ludie", "Ensminger"},
            {"Clorinda", "Marcelino"},
            {"Zora", "Peralto"},
            {"Chan", "Tippins"},
            {"Erich", "Mirsky"},
            {"Raymonde", "Thiem"},
            {"Kaitlyn", "Sowder"},
            {"Aisha", "Highfield"},
            {"Michael", "Dozal"},
            {"Beatrice", "Seal"},
            {"Nita", "Dare"},
            {"Riley", "Diggs"},
            {"Gordon", "Calzada"},
            {"Mona", "Moench"},
            {"Guillermina", "Lareau"},
            {"Khadijah", "Linebaugh"},
            {"Lakisha", "Kempton"},
            {"Sumiko", "Lopez"},
            {"Claudia", "Lazenby"},
            {"Norah", "Pless"},
            {"Dewitt", "Couturier"},
            {"Donetta", "Morelli"},
            {"Danica", "Giddens"},
            {"Jill", "Whiting"},
            {"Kylee", "Lezama"},
            {"Ramonita", "Pavlick"},
            {"Silvia", "Eichenlaub"},
            {"Shanda", "Mcnitt"},
            {"Lauralee", "Straker"},
            {"Theodora", "Dorey"},
            {"Randal", "Riles"},
            {"Fran", "Dussault"},
            {"Sharri", "Hosey"},
            {"Crissy", "Corella"},
            {"Bo", "Minich"},
            {"Candida", "Stickley"},
            {"Chelsie", "Shinault"},
            {"Glennis", "Abril"},
            {"Ta", "Stringfield"},
            {"Karine", "Olberding"},
            {"Camille", "Corp"},
            {"Jennell", "Zarrella"},
            {"Elda", "Litt"},
            {"Devona", "Dewitt"},
            {"Terisa", "Slaven"},
            {"Santana", "Tripoli"},
            {"Antwan", "Pierre"},
            {"Tammera", "Shanks"},


    };
}
