package com.zka.lyceena.constants;

public class StaticData {


    public static final String[][] PARENTS = {{"Nida", "Posner"},
            {"Jamel", "Ayari"},
            {"Jawher", "Youssfi"},
            {"Mohamed Ali", "Ben Ammar"},
            {"Youssef", "Aloui"},
            {"Ahmed", "El Mekki"}
    };
    public static final String[] FIRST_NAMES = {"Kathleen",
            "Cristofer",
            "Amiyah",
            "Dayanara",
            "Jaylee",
            "Ezra",
            "Marshall",
            "Benjamin",
            "Mohamed",
            "Efrain",
            "Madalyn",
            "Brennan",
            "Mariela",
            "Aurora",
            "Campbell",
            "Josh",
            "Shelby",
            "Mattie",
            "Emmett",
            "Jax",
            "Jessie",
            "Jaelyn",
            "Ethan",
            "Bryan",
            "Amira",
            "Tristen",
            "Mariyah",
            "Alexandria",
            "Patricia",
            "Micheal",
            "Branden",
            "Matthew",
            "Micah",
            "Mikaela",
            "Dayton",
            "Mateo",
            "Heath",
            "Felipe",
            "Elliana",
            "Russell",
            "Avery",
            "Camryn",
            "Steven",
            "Samara",
            "Alisa",
            "Annika",
            "Bianca",
            "Malachi",
            "Wesley",
            "Dustin",
            "Philip",
            "Anya",
            "Kaylen",
            "Cristina",
            "Raymond",
            "Leyla",
            "Michael",
            "Tristan",
            "Averie",
            "Jordyn",
            "Noah",
            "Alvin",
            "Reese",
            "Aniyah",
            "Alejandro",
            "Keyon",
            "Lexi",
            "Lauren",
            "Keith",
            "Jerimiah",
            "Larry",
            "Miracle",
            "Jolie",
            "Nathan",
            "Conrad",
            "Princess",
            "Averi",
            "Eddie",
            "Reginald",
            "Reed",
            "Jeffery",
            "Mareli",
            "Valerie",
            "Anabella",
            "Donte",
            "King",
            "Karsyn",
            "Paige",
            "Trinity",
            "Humberto",
            "Layton",
            "Brenton",
            "Leticia",
            "Clarence",
            "Konner",
            "Mike",
            "Sydney",
            "Evan",
            "Elvis",
            "Angel"};
    public static final String[] LAST_NAMES = {"Lucas",
            "Robertson",
            "Snow",
            "Terrell",
            "Green",
            "Combs",
            "Alvarado",
            "Marks",
            "Terry",
            "Cameron",
            "Rasmussen",
            "Valentine",
            "Bennett",
            "Koch",
            "Melton",
            "Baldwin",
            "Zhang",
            "Dominguez",
            "Curtis",
            "Kemp",
            "Hansen",
            "Thomas",
            "Fitzgerald",
            "Miranda",
            "May",
            "Richardson",
            "Mcmahon",
            "Sutton",
            "Chandler",
            "Romero",
            "Castro",
            "Patrick",
            "Crosby",
            "Sloan",
            "Morales",
            "Joseph",
            "Cabrera",
            "Hendricks",
            "Smith",
            "Bradley",
            "Palmer",
            "Arroyo",
            "Lynn",
            "Horne",
            "Ho",
            "Johnston",
            "Payne",
            "Petty",
            "Rice",
            "Pacheco",
            "Klein",
            "Guerra",
            "Donovan",
            "Osborne",
            "Stephens",
            "Hays",
            "Liu",
            "Hernandez",
            "Mathis",
            "Robles",
            "Roman",
            "Tyler",
            "Guzman",
            "Cobb",
            "Farley",
            "Mathews",
            "Woodward",
            "Manning",
            "Walton",
            "Bryan",
            "Cantrell",
            "Small",
            "Duke",
            "Hunt",
            "Stanley",
            "Campos",
            "Larsen",
            "Hutchinson",
            "Miller",
            "Strong",
            "Snyder",
            "Johns",
            "Mann",
            "Cooke",
            "Kelley",
            "Spence",
            "Ali",
            "Nash",
            "Dickerson",
            "Michael",
            "Johnson",
            "Frye",
            "Bullock",
            "Berry",
            "Phillips",
            "Underwood",
            "Fowler",
            "Acevedo",
            "Hodge",
            "Schultz"};
    public static final String[] SEXES = {"F", "M"};
    public static final String[] CLASS_LEVELS_REF_NAMES = {
            "1 Base",
            "2 Base",
            "3 Base",
            "4 Base",
            "6 Base",
            "6 Base",
            "7 Base",
            "8 Base",
            "9 Base",
            "1 Secondaire",
            "2 Secondaire Sc",
            "2 Secondaire Lettre",
            "2 Secondaire Eco",
            "2 Secondaire Info",
            "3 Secondaire Sc Exp",
            "3 Secondaire Sc Tech",
            "3 Secondaire Sc Math",
            "3 Secondaire Lettre",
            "3 Secondaire Eco",
            "3 Secondaire Info",
            "BAC Secondaire Sc Exp",
            "BAC Secondaire Sc Tech",
            "BAC Secondaire Sc Math",
            "BAC Secondaire Lettre",
            "BAC Secondaire Eco",
            "BAC Secondaire Info",
    };
    public static final String[] MATERIALS_REF_NAMES = {
            "Mathématique",
            "SVT",
            "Physique",
            "Technique",
            "Education physique",
            "Informatique",
            "Français",
            "Anglais",
            "تفكير إسلامي",
            "Arabe",
            "Economies",
            "Gestion",
            "تربية مدنية",
            "فلسفة",
            "تاريخ و جغرافيا"
    };

    public static final String[][] DAYS = {
            {"Monday", "Lundi", ""},
            {"Tuesday", "Mardi", ""},
            {"Wednesday", "Mercredi", ""},
            {"Thursday", "Jeudi", ""},
            {"Friday", "Vendredi", ""},
            {"Satuday", "Samedi", ""},
            {"Sunday", "Dimanche", ""},
    };

    public static final String[] HOURS = {
            "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00"
    };

    public static final String[] FORBIDDEN_START_HOURS = {
             "18:00"
    };

    public static final String[][] TEACHERS = {

            {"Fatma", "Mseddi"},
            {"Mohamed", "Ben Mostafa"},
            {"Zouhaier", "Dhawadi"},
            {"Youssef", "Msekni"},
            {"Khaled", "Badra"},
            {"Ghazi", "Ayadi"},
            {"Wissem", "Yahya"},
            {"Bilel", "Ifaa"},
            {"Chamseddin", "Dhaouadi"},
            {"Filiberto", "Rosemond"},
            {"Kimberley", "Avilla"},
            {"Pamala", "Abe"},
            {"Clarissa", "Coniglio"},
            {"Anissa", "Devinney"},
            {"Mitzi", "Tillis"},
            {"Kelly", "Ballance"},
            {"Sarina", "Landrum"},
            {"Mable", "Maury"},
            {"Latoyia", "Bently"},
            {"Shonda", "Wind"},
            {"Andrew", "Guth"},
            {"Elisha", "Chumbley"},
            {"Armand", "Odriscoll"},
            {"Nelida", "Natal"},
            {"Enriqueta", "Zito"},
            {"Deja", "Pitzen"},
            {"Cornell", "Empey"},
            {"Margarete", "Harrelson"},
            {"Kendall", "Carl"},
            {"Vena", "Crane"},
            {"Leonel", "Conger"},
            {"Mike", "Isakson"},
            {"Otha", "Demma"}};


    private StaticData() {
    }
}
