package com.zka.lyceena.constants;

public class StaticData {


    private StaticData(){}


    public static final String[][] PARENTS = {{"Nida", "Posner"},
            {"Jamel", "Ayari"},
            {"Jawher", "Youssfi"},
            {"Mohamed Ali", "Ben Ammar"},
            {"Youssef", "Aloui"},
            {"Ahmed", "El Mekki"}
    };

    public static final String[][] TEACHERS = {
            {"Mickie", "Messersmith"},
            {"Juliet", "Abdallah"},
            {"Evette", "Reasoner"},
            {"Rosella", "Vessels"},
            {"Milan", "Bulmer"},
            {"Victor", "Pontius"},
            {"Santiago", "Direnzo"},
            {"Catharine", "Neel"},
            {"Werner", "Hammell"},
            {"Sabina", "Dreier"},
    };

    public static final String[] FIRST_NAMES = {"Kathleen",
            "Cristofer",
            "Amiyah",
            "Dayanara",
            "Jaylee",
            "Ezra",
            "Marshall",
            "Benjamin",
            "Mohamed",
            "Efrain",
            "Madalyn",
            "Brennan",
            "Mariela",
            "Aurora",
            "Campbell",
            "Josh",
            "Shelby",
            "Mattie",
            "Emmett",
            "Jax",
            "Jessie",
            "Jaelyn",
            "Ethan",
            "Bryan",
            "Amira",
            "Tristen",
            "Mariyah",
            "Alexandria",
            "Patricia",
            "Micheal",
            "Branden",
            "Matthew",
            "Micah",
            "Mikaela",
            "Dayton",
            "Mateo",
            "Heath",
            "Felipe",
            "Elliana",
            "Russell",
            "Avery",
            "Camryn",
            "Steven",
            "Samara",
            "Alisa",
            "Annika",
            "Bianca",
            "Malachi",
            "Wesley",
            "Dustin",
            "Philip",
            "Anya",
            "Kaylen",
            "Cristina",
            "Raymond",
            "Leyla",
            "Michael",
            "Tristan",
            "Averie",
            "Jordyn",
            "Noah",
            "Alvin",
            "Reese",
            "Aniyah",
            "Alejandro",
            "Keyon",
            "Lexi",
            "Lauren",
            "Keith",
            "Jerimiah",
            "Larry",
            "Miracle",
            "Jolie",
            "Nathan",
            "Conrad",
            "Princess",
            "Averi",
            "Eddie",
            "Reginald",
            "Reed",
            "Jeffery",
            "Mareli",
            "Valerie",
            "Anabella",
            "Donte",
            "King",
            "Karsyn",
            "Paige",
            "Trinity",
            "Humberto",
            "Layton",
            "Brenton",
            "Leticia",
            "Clarence",
            "Konner",
            "Mike",
            "Sydney",
            "Evan",
            "Elvis",
            "Angel"};

    public static final String[] LAST_NAMES = {"Lucas",
            "Robertson",
            "Snow",
            "Terrell",
            "Green",
            "Combs",
            "Alvarado",
            "Marks",
            "Terry",
            "Cameron",
            "Rasmussen",
            "Valentine",
            "Bennett",
            "Koch",
            "Melton",
            "Baldwin",
            "Zhang",
            "Dominguez",
            "Curtis",
            "Kemp",
            "Hansen",
            "Thomas",
            "Fitzgerald",
            "Miranda",
            "May",
            "Richardson",
            "Mcmahon",
            "Sutton",
            "Chandler",
            "Romero",
            "Castro",
            "Patrick",
            "Crosby",
            "Sloan",
            "Morales",
            "Joseph",
            "Cabrera",
            "Hendricks",
            "Smith",
            "Bradley",
            "Palmer",
            "Arroyo",
            "Lynn",
            "Horne",
            "Ho",
            "Johnston",
            "Payne",
            "Petty",
            "Rice",
            "Pacheco",
            "Klein",
            "Guerra",
            "Donovan",
            "Osborne",
            "Stephens",
            "Hays",
            "Liu",
            "Hernandez",
            "Mathis",
            "Robles",
            "Roman",
            "Tyler",
            "Guzman",
            "Cobb",
            "Farley",
            "Mathews",
            "Woodward",
            "Manning",
            "Walton",
            "Bryan",
            "Cantrell",
            "Small",
            "Duke",
            "Hunt",
            "Stanley",
            "Campos",
            "Larsen",
            "Hutchinson",
            "Miller",
            "Strong",
            "Snyder",
            "Johns",
            "Mann",
            "Cooke",
            "Kelley",
            "Spence",
            "Ali",
            "Nash",
            "Dickerson",
            "Michael",
            "Johnson",
            "Frye",
            "Bullock",
            "Berry",
            "Phillips",
            "Underwood",
            "Fowler",
            "Acevedo",
            "Hodge",
            "Schultz"};

    public static final String [] SEXES = {"F","M"};
}
